#!/usr/bin/env bash
# Curated macOS defaults. Each setting is a `defaults write` so it can be
# reversed with the same key + `defaults delete` (or revert by re-running
# System Settings adjustments). Re-running this script is idempotent.
#
# Every setting is applied through `apply_default`, which captures the prior
# state first and records the inverse command in a generated undo script at
# ${UNDO} so the changes are self-documenting and reversible.

set -euo pipefail

echo "→ Applying macOS defaults..."

# ── Undo log ──────────────────────────────────────────────────────────────────
# Path to the generated undo script. Truncated on every run so re-running this
# script always regenerates a fresh undo log rather than appending to a stale
# one (keeping the whole thing idempotent).
UNDO="${HOME}/.workstation-defaults-undo.sh"

cat > "${UNDO}" <<'EOF'
#!/usr/bin/env bash
# Generated by macos/defaults.sh -- do not edit by hand.
# Re-running defaults.sh regenerates this file. Running it restores the
# macOS defaults to the state they were in just before defaults.sh last ran.

set -euo pipefail

echo "→ Restoring previous macOS defaults..."
EOF

# apply_default <domain> <key> <type> <value>
# Records the inverse of the pending change in the undo script, then performs
# the actual `defaults write`. If the key was previously set, the undo line
# restores the old value with the same type flag; if it was unset, the undo
# line deletes the key.
apply_default() {
  local domain="$1" key="$2" type="$3" value="$4"
  local old=""
  local was_set="true"

  # A missing key makes `defaults read` exit non-zero; guard it so the outer
  # `set -e` doesn't abort the script.
  old="$(defaults read "${domain}" "${key}" 2>/dev/null)" || was_set="false"

  if [[ "${was_set}" == "true" ]]; then
    # `defaults read` prints booleans as 1/0, but the `-bool` flag only accepts
    # true/false/yes/no, so normalize before writing the undo line. Other types
    # (-int/-float/-string) round-trip cleanly.
    if [[ "${type}" == "-bool" ]]; then
      [[ "${old}" == "1" ]] && old="true" || old="false"
    fi
    printf 'defaults write %q %q %s %q\n' "${domain}" "${key}" "${type}" "${old}" >> "${UNDO}"
  else
    printf 'defaults delete %q %q\n' "${domain}" "${key}" >> "${UNDO}"
  fi

  defaults write "${domain}" "${key}" "${type}" "${value}"
}

# ── Keyboard ────────────────────────────────────────────────────────────────
# Faster key repeat (smallest values; defaults are 6 / 25 in System Settings).
apply_default NSGlobalDomain KeyRepeat -int 2
apply_default NSGlobalDomain InitialKeyRepeat -int 15

# Note: ApplePressAndHoldEnabled is left at the macOS default. Disabling it
# would let vim h/j/k/l repeat in some terminal editors, but it also breaks
# the press-and-hold accent menu, which is more useful day-to-day. Arrow
# keys still repeat fine in Vim regardless.

# ── Screenshots ─────────────────────────────────────────────────────────────
mkdir -p "${HOME}/Pictures/Screenshots"
apply_default com.apple.screencapture location -string "${HOME}/Pictures/Screenshots"
apply_default com.apple.screencapture type -string "png"
# Window-screenshot drop shadow stays enabled (macOS default) per user
# preference -- the shadow is part of the desired aesthetic.

# ── Finder ──────────────────────────────────────────────────────────────────
apply_default NSGlobalDomain AppleShowAllExtensions -bool true
# Hidden files stay hidden by default (use Cmd+Shift+. to toggle per-window).
apply_default com.apple.finder ShowPathbar -bool true
apply_default com.apple.finder ShowStatusBar -bool true
# View styles: icnv=Icon, Nlsv=List, clmv=Column, glyv=Gallery.
apply_default com.apple.finder FXPreferredViewStyle -string "clmv"  # column view default
apply_default com.apple.finder _FXSortFoldersFirst -bool true
apply_default com.apple.finder FXDefaultSearchScope -string "SCcf"  # search current folder by default

# ── Dock ────────────────────────────────────────────────────────────────────
apply_default com.apple.dock autohide -bool true
apply_default com.apple.dock autohide-time-modifier -float 0.4
apply_default com.apple.dock autohide-delay -float 0
apply_default com.apple.dock show-recents -bool false
# minimize-to-application stays at default (false) -- minimized windows
# remain as separate previews on the right side of the Dock rather than
# collapsing into their app icon.

# ── Save / Print dialogs ────────────────────────────────────────────────────
apply_default NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
apply_default NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
apply_default NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
apply_default NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# ── Misc ──────────────────────────────────────────────────────────────────────
# Don't write .DS_Store on network/USB volumes.
apply_default com.apple.desktopservices DSDontWriteNetworkStores -bool true
apply_default com.apple.desktopservices DSDontWriteUSBStores -bool true

# Finalize the undo script: restart the same services so restored values take
# effect, then make it executable so the user can run it directly.
cat >> "${UNDO}" <<'EOF'

# Restart affected services so restored values take effect immediately.
killall Dock Finder SystemUIServer 2>/dev/null || true

echo "✓ Previous macOS defaults restored."
EOF
chmod +x "${UNDO}"

# Restart affected services so changes take effect immediately.
killall Dock Finder SystemUIServer 2>/dev/null || true

echo "✓ macOS defaults applied. Some changes (e.g. KeyRepeat) require a logout/login."
echo "  To undo these changes, run: ${UNDO}"
